# Generated by Django 2.2.1 on 2019-05-09 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='姓名')),
                ('age', models.CharField(max_length=200, verbose_name='年龄')),
                ('sex', models.CharField(max_length=10, verbose_name='性别')),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('major', models.CharField(max_length=3, verbose_name='专业')),
                ('prof', models.BooleanField(verbose_name='专家')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
